site_name: Dig-Docs

nav:
 - Home: index.md
 - Introduction: intro.md
 - Slow Control: slow-control.md
 - COMM&Sensors:
   - LEDs: control/leds.md
   - Sensors: control/sensors.md
   - Peripherals: control/onboard-peripherals.md
 - Setup:
   - DAQ Parameters: setup/parameters.md
   - Pedestal: setup/pedestal.md
   - Calibrator: setup/calibrator.md
   - HW setup: setup/hw-setup.md
 - DAQ:
   - Data Format: daq/data-format.md
   - Settings: daq/board-control.md
   - Timing: daq/timing.md
 - ________:
   - Appendix: appenidx/appendix.md
    - COPackkt: appendix/dig-protocols.md
    - dpb-slowcontrolapp: appendix/dpb-slowcontrolapp.md
 - About: about.md

markdown_extensions:
  - toc:
      permalink: "#"

theme: readthedocs
