site_name: Dig-Docs

nav:
 - Home: index.md
 - Introduction: intro.md
 - Slow Control: slow-control.md
 - COMM&Sensors:
   - LEDs: control/leds.md
   - Sensors: control/sensors.md
   - Peripherals: control/onboard-peripherals.md
 - Setup:
   - DAQ Parameters: setup/parameters.md
   - Pedestal: setup/pedestal.md
   - Calibrator: setup/calibrator.md
   - HW setup: setup/hw-setup.md
 - DAQ:
   - Data Format: daq/data-format.md
   - Settings: daq/board-control.md
   - Timing: daq/timing.md
 - Appendix:
   - DIG-DPB serial bridge: appendix/dig-dpb-bridge.md
   - DIG protocols: appendix/dig-protocols.md
   - DPB slow control service: appendix/dpb-slowcontrol-service.md
 - About: about.md

markdown_extensions:
  - toc:
      permalink: "#"

theme: readthedocs
